import SideBar from "@/components/SideBar/SideBar";
import SideBarRight from "@/components/SidebarRight/SideBarRight";
import Header from "@/components/common/Header";
import CommentModal from "@/components/modals/CommentModal";
import JotModal from "@/components/modals/JotModal";
import SyncClient from "@/components/synchronize/SyncClient";

import "@/styles/globals.css";
import { getServerSession } from "next-auth";

import { Inter } from "next/font/google";
import getUserId from "@/libs/getUserId";
import PostDeleteModal from "@/components/modals/PostDeleteModal";
import EditModal from "@/components/modals/EditModal";
import { authOptions } from "../api/auth/[...nextauth]/route";
import Toaster from "@/components/Toasts/Toaster";
import Scroller from "@/components/common/Scroller";
import SearchModal from "@/components/modals/SearchModal";
import TimerModal from "@/components/modals/TimerModal";
import TakeaBreakModal from "@/components/modals/TakeaBreakModal";
import EmailVerificiation from "@/components/verification/EmailVerificiation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  let loggedUserId = null;

  if (session?.user?.email && !session?.user?.emailVerified) {
    return (
      <>
        <EmailVerificiation />
      </>
    );
  }

  if (session?.user?.email) {
    loggedUserId = await getUserId(session.user.email);
  }

  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${inter?.className} scroll-smooth`}
    >
      <body>
        {loggedUserId && <SyncClient />}
        <JotModal />
        <CommentModal />
        <PostDeleteModal />
        <EditModal />
        <SearchModal />
        <TimerModal />
        <TakeaBreakModal />
        <Toaster />
        <div className="xl:px-[5%] px-0 ">
          <Header loggedUserId={loggedUserId} />
          <main className="md:p-2 p-1 h-[89vh]">
            <div className="flex  h-full w-full gap-x-4">
              <div className="basis-1/3   overflow-x-hidden overflow-y-scroll hidden md:flex">
                {/* sidebar */}
                <SideBar loggedUserId={loggedUserId} />
              </div>
              <div className="basis-2/3 flex-1 overflow-y-auto  h-full  bg-base-200 rounded-box pb-4 xl:px-[2%] lg:px-[1%] md:px-2 sm:px-4">
                {children}
              </div>
              <div className="xl:flex hidden basis-1/3 overflow-auto bg-base-200 rounded-box">
                {/* extra */}
                <SideBarRight />
              </div>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
